version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
  backend:
    build: .
    depends_on: [mongo]
    environment:
      - MONGO_URI=mongodb://mongo:27017/concert_reg
      - JWT_SECRET=change_this_secret
      - ADMIN_USERNAME=dan
      - ADMIN_PASSWORD=dan123
    ports:
      - "5000:5000"
volumes:
  mongo-data:
